server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yuntest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    #jdbc:mysql://localhost:3306/yuntest?characterEncoding=utf8
    username: root
    password: 1234567
    driver-class-name:   com.mysql.cj.jdbc.Driver
    #com.mysql.jdbc.Driver 已经弃用
#    type:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

      #Redis配置
  redis:
   # database: 0
    host: 192.168.146.200 #192.168.146.200
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
    timeout: 5000
  data:
  #mongodb配置
    mongodb:
      uri: mongodb://192.168.146.200:27017/test




























