server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/yuntest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
#    #jdbc:mysql://localhost:3306/yuntest?characterEncoding=utf8
#    username: root
#    password: 1234567
#    driver-class-name:   com.mysql.cj.jdbc.Driver
#    #com.mysql.jdbc.Driver 已经弃用
##    type:
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: update

























